### ISSUE TITLE
It doesn't recognize POST body object on Windows

### ISSUE THREAD

**Issue by David-Pena** [danirod/cartero#23]
I just downloaded the windows and tried to execute a common POST request that I use but didnt work, I'm not sure maybe Im indenting wrong or something like that

This is the request in postman
![image](https://github.com/danirod/cartero/assets/57303087/538281cd-165b-42b4-9aa6-badd17c5b682)

This is the request in Cartero:
![image](https://github.com/danirod/cartero/assets/57303087/55a7fd64-33a9-4849-a724-a1f6e2c25416)

**Comment by danirod** [comment]
Here is what I think it's happening: When you use Postman and set the body type to Raw/JSON, Postman seems to automatically add an implicit `Content-Type` header with the value of `application/json`.

![The Postman headers of a JSON request](https://github.com/danirod/cartero/assets/1568690/46eb7548-aaaa-41b7-8e12-8f3437f73bcb)

Until https://github.com/danirod/cartero/pull/21 is finished, which will a proper way of setting the payload format in the Body tab, it may be required to manually add the `Content-Type` header with the value of `application/json` for a web server to actually understand that a request body is JSON, otherwise most servers will not figure it out.

![imagen](https://github.com/danirod/cartero/assets/1568690/33cb93ee-8134-44f3-a021-0b7c54c48d6e)

**Comment by David-Pena** [comment]
Indeed, that was the problem. I just added the header and it worked
![image](https://github.com/danirod/cartero/assets/57303087/53cbeb5e-1ddb-47d1-aad7-e4107c4cfdbc)
Thanks for the help and good luck with cartero!!
