### ISSUE TITLE
Broken links in "About Cartero" section

### ISSUE THREAD

**Issue by richardogcc** [danirod/cartero#43]
I've noticed that the links in the "About Cartero" section are not functioning properly. When I click on them, I'm not taken to the expected webpage or resource.

![image](https://github.com/user-attachments/assets/c8bb6a66-117b-492b-a38b-a6b54f6c5a5e)

### Steps to reproduce:
- Open the Cartero application.
- Navigate to the "About Cartero" section.
- Click on any of the links provided.
- Observe that the link does not work as expected.

### Expected behavior:
The links in the "About Cartero" section should be functional and take the user to the intended webpage or resource.

### System information:
Operating System: Windows 11 PRO (23H2)

Let me know if you'd like me to add or modify anything!

**Comment by danirod** [comment]
After some research, it seems that GTK uses a separate executable called `gspawn-win64-helper.exe` to handle things like clicking links.

It is not being packed in the Windows version, therefore nothing is going to happen because it seems that it doesn't show an error in that case. (Something that [appears to be fixed in the next GTK version](https://gitlab.gnome.org/GNOME/gtk/-/issues/6446)).

I did not catch this earlier because of course if I run the application in MSYS2, gspawn-win64-helper.exe will be in the shell PATH and thus it will always work.
